In [13]:
import pandas as pd

df = pd.read_csv("github_top_repositories.csv")

print(f"Rows before deduplication: {len(df)}")
print(f"Duplicate repositories by Full Name: {df['Full Name'].duplicated().sum()}")

df = df.drop_duplicates(subset='Full Name').copy()

print(f"Rows after deduplication: {len(df)}")

Rows before deduplication: 3000
Duplicate repositories by Full Name: 438
Rows after deduplication: 2562

In [14]:
df.head(5)

,Domain,Repository Name,Full Name,Description,Primary Language,Stars Count,Forks Count,Watchers Count,Open Issues Count,Has Wiki,...,Has Projects,Size (KB),Created At,Updated At,Pushed At,Default Branch,Owner Login,Owner Type,License,Topics
0,Machine Learning,tensorflow,tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,C++,194126,75247,194126,3715,False,...,True,1288956,2015-11-07T01:19:20Z,2026-03-14T00:28:29Z,2026-03-14T01:48:00Z,master,tensorflow,Organization,Apache License 2.0,"deep-learning, deep-neural-networks, distribut..."
1,Machine Learning,transformers,huggingface/transformers,🤗 Transformers: the model-definition framework...,Python,157772,32464,157772,2282,True,...,True,453964,2018-10-29T13:56:00Z,2026-03-14T01:38:18Z,2026-03-13T23:15:04Z,main,huggingface,Organization,Apache License 2.0,"audio, deep-learning, deepseek, gemma, glm, ha..."
2,Machine Learning,prompts.chat,f/prompts.chat,"f.k.a. Awesome ChatGPT Prompts. Share, discove...",HTML,152186,19999,152186,28,True,...,True,231182,2022-12-05T13:54:13Z,2026-03-14T02:08:32Z,2026-03-13T14:06:54Z,main,f,User,Creative Commons Zero v1.0 Universal,"ai, artificial-intelligence, awesome-list, cha..."
3,Machine Learning,pytorch,pytorch/pytorch,Tensors and Dynamic neural networks in Python ...,Python,98216,27194,98216,18055,True,...,True,1273608,2016-08-13T05:26:41Z,2026-03-14T01:40:49Z,2026-03-14T02:08:49Z,main,pytorch,Organization,Other,"autograd, deep-learning, gpu, machine-learning..."
4,Machine Learning,LLMs-from-scratch,rasbt/LLMs-from-scratch,Implement a ChatGPT-like LLM in PyTorch from s...,Jupyter Notebook,87955,13422,87955,1,False,...,False,15703,2023-07-23T18:15:57Z,2026-03-14T02:06:45Z,2026-03-07T23:05:50Z,main,rasbt,User,Other,"ai, artificial-intelligence, chatbot, chatgpt,..."

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 2562 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Domain             2562 non-null   str
 1   Repository Name    2562 non-null   str
 2   Full Name          2562 non-null   str
 3   Description        2556 non-null   str
 4   Primary Language   2354 non-null   str
 5   Stars Count        2562 non-null   int64
 6   Forks Count        2562 non-null   int64
 7   Watchers Count     2562 non-null   int64
 8   Open Issues Count  2562 non-null   int64
 9   Has Wiki           2562 non-null   bool
 10  Has Pages          2562 non-null   bool
 11  Has Projects       2562 non-null   bool
 12  Size (KB)          2562 non-null   int64
 13  Created At         2562 non-null   str
 14  Updated At         2562 non-null   str
 15  Pushed At          2562 non-null   str
 16  Default Branch     2562 non-null   str
 17  Owner Login        2562 non-null   str
 18  Owner Type         2562 non-null   str
 19  License            2293 non-null   str
 20  Topics             2365 non-null   str
dtypes: bool(3), int64(5), str(13)
memory usage: 387.8 KB

In [16]:
df = df.drop(["Repository Name", "Full Name", "Description", "Owner Login", "Topics"], axis="columns")
df.drop(['Watchers Count'], axis='columns', inplace=True) # Пришлось удалить из-за проблемы датасета, что Stars count == Watchers count
df.info()

<class 'pandas.DataFrame'>
Index: 2562 entries, 0 to 2999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Domain             2562 non-null   str
 1   Primary Language   2354 non-null   str
 2   Stars Count        2562 non-null   int64
 3   Forks Count        2562 non-null   int64
 4   Open Issues Count  2562 non-null   int64
 5   Has Wiki           2562 non-null   bool
 6   Has Pages          2562 non-null   bool
 7   Has Projects       2562 non-null   bool
 8   Size (KB)          2562 non-null   int64
 9   Created At         2562 non-null   str
 10  Updated At         2562 non-null   str
 11  Pushed At          2562 non-null   str
 12  Default Branch     2562 non-null   str
 13  Owner Type         2562 non-null   str
 14  License            2293 non-null   str
dtypes: bool(3), int64(4), str(8)
memory usage: 267.7 KB

In [17]:
nan_matrix = df.isnull()
print(nan_matrix.sum())

Domain                 0
Primary Language     208
Stars Count            0
Forks Count            0
Open Issues Count      0
Has Wiki               0
Has Pages              0
Has Projects           0
Size (KB)              0
Created At             0
Updated At             0
Pushed At              0
Default Branch         0
Owner Type             0
License              269
dtype: int64

In [18]:
df.fillna({'Primary Language' : 'Unknown', 'License' : 'Unknown'},inplace=True)

nan_matrix = df.isnull()
print(nan_matrix.sum())

Domain               0
Primary Language     0
Stars Count          0
Forks Count          0
Open Issues Count    0
Has Wiki             0
Has Pages            0
Has Projects         0
Size (KB)            0
Created At           0
Updated At           0
Pushed At            0
Default Branch       0
Owner Type           0
License              0
dtype: int64

In [19]:
for col in df.columns:
    number_unique = df[col].nunique()
    print(f"{col} : {number_unique}")

Domain : 15
Primary Language : 55
Stars Count : 2462
Forks Count : 1988
Open Issues Count : 809
Has Wiki : 2
Has Pages : 2
Has Projects : 2
Size (KB) : 2507
Created At : 2562
Updated At : 2504
Pushed At : 2555
Default Branch : 69
Owner Type : 2
License : 22

In [20]:
num_cols = ['Forks Count', 'Open Issues Count', 'Size (KB)']

for col in num_cols:
    print(f"{col}: min={df[col].min()}, max={df[col].max()}")


df['Created At'] = pd.to_datetime(df['Created At']).dt.tz_localize(None)
df['Updated At'] = pd.to_datetime(df['Updated At']).dt.tz_localize(None)
df['Pushed At'] = pd.to_datetime(df['Pushed At']).dt.tz_localize(None)

date_cols = ['Created At', 'Updated At', 'Pushed At']
for col in date_cols:
    print(f"{col}: min={df[col].min()}, max={df[col].max()}")

Forks Count: min=4, max=75247
Open Issues Count: min=0, max=18055
Size (KB): min=2, max=61838464
Created At: min=2008-09-02 05:34:33, max=2026-03-06 22:00:43
Updated At: min=2024-11-01 00:54:36, max=2026-03-14 02:23:25
Pushed At: min=2016-03-09 11:44:35, max=2026-03-14 02:23:17

In [21]:
df['Forks_Bin'] = pd.qcut(df['Forks Count'], q=10, labels=False)
df['Open_Issues_Bin'] = pd.qcut(df['Open Issues Count'], q=10, labels=False)
df['Size(KB)_Bin'] = pd.qcut(df['Size (KB)'], q=10, labels=False)

reference_day = pd.Timestamp('2026-03-14')

# Переводим даты в количество дней от референс дня
df['Created_Days'] = (reference_day - df['Created At']).dt.days
df['Updated_Days'] = (reference_day - df['Updated At']).dt.days
df['Pushed_Days'] = (reference_day - df['Pushed At']).dt.days

# Категоризация по бинам
df['Created_Bin'] = pd.qcut(df['Created_Days'], q=10, labels=False)
df['Updated_Bin'] = pd.qcut(df['Updated_Days'], q=10, labels=False, duplicates='drop')
df['Pushed_Bin'] = pd.qcut(df['Pushed_Days'], q=10, labels=False, duplicates='drop')

df.drop(['Forks Count', 'Open Issues Count', 'Size (KB)', 'Created_Days',
     'Updated_Days', 'Pushed_Days', 'Created At', 'Updated At', 'Pushed At'], axis="columns", inplace=True)

for col in df.columns:
    number_unique = df[col].nunique()
    print(f"{col} : {number_unique}")

Domain : 15
Primary Language : 55
Stars Count : 2462
Has Wiki : 2
Has Pages : 2
Has Projects : 2
Default Branch : 69
Owner Type : 2
License : 22
Forks_Bin : 10
Open_Issues_Bin : 10
Size(KB)_Bin : 10
Created_Bin : 10
Updated_Bin : 4
Pushed_Bin : 9

In [22]:
# Бинарные признаки переводим в 0/1 для модели
bool_cols = ['Has Wiki', 'Has Pages', 'Has Projects']
df[bool_cols] = df[bool_cols].astype(int)

# Для ветки достаточно оставить main/master/other
df['Default Branch'] = df['Default Branch'].where(
    df['Default Branch'].isin(['main', 'master']),
    'other'
)

# Organization=1, User=0
df['Owner Type'] = (df['Owner Type'] == 'Organization').astype(int)

# One-hot encoding
categorical_cols = ['Domain', 'Primary Language', 'License', 'Default Branch']
df = pd.get_dummies(df, columns=categorical_cols, dtype=int, drop_first=True)

print(df.shape)
df.head()

(2562, 102)

,Stars Count,Has Wiki,Has Pages,Has Projects,Owner Type,Forks_Bin,Open_Issues_Bin,Size(KB)_Bin,Created_Bin,Updated_Bin,...,License_GNU Lesser General Public License v3.0,License_ISC License,License_MIT License,License_Mozilla Public License 2.0,License_Other,License_The Unlicense,License_Unknown,License_zlib License,Default Branch_master,Default Branch_other
0,194126,0,0,1,1,9,9,9,7,0,...,0,0,0,0,0,0,0,0,1,0
1,157772,1,0,1,1,9,9,9,4,0,...,0,0,0,0,0,0,0,0,0,0
2,152186,1,1,1,0,9,2,8,1,0,...,0,0,0,0,0,0,0,0,0,0
3,98216,1,0,1,1,9,9,9,6,0,...,0,0,0,0,1,0,0,0,0,0
4,87955,0,0,0,0,9,0,3,0,0,...,0,0,0,0,1,0,0,0,0,0

In [23]:
import numpy as np

df['Stars Count'] = np.log1p(df['Stars Count'])
print(df['Stars Count'])

0       12.176268
1       11.968913
2       11.932865
3       11.494935
4       11.384592
          ...
2994     7.647309
2995     7.643483
2997     7.624619
2998     7.602401
2999     7.601402
Name: Stars Count, Length: 2562, dtype: float64

In [24]:
df.to_csv('processed_data.csv', index=False)